src/Entity/Reservationfleur.php
<?php

namespace App\Entity;

use App\Repository\ReservationfleurRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReservationfleurRepository::class)
 */
class Reservationfleur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     */
    private $user;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbr_personne;

    /**
     * @ORM\Column(type="datetime")
     */
    private $start_date;

    /**
     * @ORM\Column(type="datetime")
     */
    private $end_date;

    /**
     * @ORM\ManyToOne(targetEntity=Servicefleurdelys::class)
     */
    private $servicefleurdelys;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getNbrPersonne(): ?int
    {
        return $this->nbr_personne;
    }

    public function setNbrPersonne(int $nbr_personne): self
    {
        $this->nbr_personne = $nbr_personne;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getServicefleurdelys(): ?Servicefleurdelys
    {
        return $this->servicefleurdelys;
    }

    public function setServicefleurdelys(?Servicefleurdelys $servicefleurdelys): self
    {
        $this->servicefleurdelys = $servicefleurdelys;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

src/Form/ReservationfleurType.php
<?php

namespace App\Form;

use App\Entity\User;
use App\Entity\Reservationfleur;
use App\Entity\Servicefleurdelys;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;

class ReservationfleurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('user', EntityType::class,['class'=>User::class,
        'choice_label'=>'nom',
       'label'=>'Votre Nom'
       ])
        ->add('nbr_personne', NumberType::class,[

            'label'=> 'Numbres des Personnes'
        ])
        ->add('start_date', DateTimeType::class, [
            'date_widget' => 'single_text'
        ])
        ->add('end_date', DateTimeType::class, [
            'date_widget' => 'single_text'
        ])
        ->add('description')
       
        
        ->add('servicefleurdelys', EntityType::class,['class'=>Servicefleurdelys::class,
        'choice_label'=>'nom',
       'label'=>'service Fleur De Lys'
   ])
    
;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Reservationfleur::class,
        ]);
    }
}

src/Controller/ReservationfleurController.php
<?php

namespace App\Controller;

use App\Entity\Reservationfleur;
use App\Form\ReservationfleurType;
use App\Repository\ReservationfleurRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/reservationfleur")
 */
class ReservationfleurController extends AbstractController
{
    /**
     * @Route("/", name="reservationfleur_index", methods={"GET"})
     */
    public function index(ReservationfleurRepository $reservationfleurRepository): Response
    {
        return $this->render('reservationfleur/index.html.twig', [
            'reservationfleurs' => $reservationfleurRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="reservationfleur_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $reservationfleur = new Reservationfleur();
        $form = $this->createForm(ReservationfleurType::class, $reservationfleur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($reservationfleur);
            $entityManager->flush();

            return $this->redirectToRoute('reservationfleur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reservationfleur/new.html.twig', [
            'reservationfleur' => $reservationfleur,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reservationfleur_show", methods={"GET"})
     */
    public function show(Reservationfleur $reservationfleur): Response
    {
        return $this->render('reservationfleur/show.html.twig', [
            'reservationfleur' => $reservationfleur,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="reservationfleur_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Reservationfleur $reservationfleur): Response
    {
        $form = $this->createForm(ReservationfleurType::class, $reservationfleur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('reservationfleur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('reservationfleur/edit.html.twig', [
            'reservationfleur' => $reservationfleur,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="reservationfleur_delete", methods={"POST"})
     */
    public function delete(Request $request, Reservationfleur $reservationfleur): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservationfleur->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($reservationfleur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('reservationfleur_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/reservationfleur/_delete_form.html.twig
<form method="post" action="{{ path('reservationfleur_delete', {'id': reservationfleur.id}) }}" onsubmit="return confirm('Êtes-vous sûr de bien vouloir supprimer cette réservation?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservationfleur.id) }}">
    <button class="btn btn-secondary">Annuler</button>
</form>
<style>

button{
   
    width:200px;
    font-size:10px;
    margin-bottom:5px;
}

</style>

templates/reservationfleur/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-secondary">{{ button_label|default('Réserver') }}</button>
{{ form_end(form) }}
<style>
button{
    
    width:200px;
    font-size:10px;
    margin-bottom:5px;
}


</style>

templates/reservationfleur/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Réservation Fleur De Lys{% endblock %} 

{% block body %}
    <h1>Modifier Réservation Fleur De Lys</h1>

    <div class="form">{{ include('reservationfleur/_form.html.twig', {'button_label': 'Modifier'}) }}</div>

   <a href="{{ path('reservationfleur_index') }}"> <button  class="btn btn-secondary" style=" margin:5px 0 100px 200px;">Voir La Liste</button></a>
    <style>
      h1{
         padding: 5%;
         font-family: 'Playfair Display', serif;
         color: rgb(252, 252, 250);
         font-size:35px;
         text-shadow: 3px 4px 0 rgba(14, 12, 12, 0.2); 
         margin-left:128px;
      }
      .form{
    margin:0 200px 0 200px;
}

button {
   
    width:200px;
    font-size:10px;
    margin-bottom:5px;
}
    </style>
{% endblock %}

templates/reservationfleur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation Fleur De Lys{% endblock %}

{% block body %}
    <h2>Réservation Fleur De Lys </h2>

    <table class="table">
        <thead>
            <tr>
                
                <th>Votre Nom</th>
                <th>Service</th>
                <th>Début_date</th>
                <th>Fin_date</th>
                <th>Nbr_personne</th>
                <th>Description</th>
                <th>Edit</th>
                <th>Annuler</th>
                <th>Confirmer</th>
                
            </tr>
        </thead>
        <tbody>
        {% for reservationfleur in reservationfleurs %}
            <tr>
                
                <td>{{ reservationfleur.User }}</td>
                <td>{{ reservationfleur.servicefleurdelys }}</td>
                <td>{{ reservationfleur.startDate ? reservationfleur.endDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ reservationfleur.endDate ? reservationfleur.startDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ reservationfleur.nbrPersonne }}</td>
                <td>{{ reservationfleur.description }}</td>
                <td><a style="color:rgb(14, 13, 13);" href="{{ path('reservationfleur_edit', {'id': reservationfleur.id}) }}"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
  <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
</svg></td>
                <td><a style="color:rgb(14, 13, 13);" href="{{ path('reservationfleur_delete', {'id': reservationfleur.id}) }}"><svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-x-lg" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M13.854 2.146a.5.5 0 0 1 0 .708l-11 11a.5.5 0 0 1-.708-.708l11-11a.5.5 0 0 1 .708 0Z"/>
  <path fill-rule="evenodd" d="M2.146 2.146a.5.5 0 0 0 0 .708l11 11a.5.5 0 0 0 .708-.708l-11-11a.5.5 0 0 0-.708 0Z"/>
</svg></a></td>
                <td><a style="color:rgb(14, 13, 13);" href="{{ path('reservationfleur_show', {'id': reservationfleur.id}) }}"><svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="currentColor" class="bi bi-check-lg" viewBox="0 0 16 16">
  <path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z"/>
</svg></a></td>
              
            </tr>
        {% else %}
            <tr>
                <td colspan="7">reservation vide</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('reservationfleur_new') }}"><button class="btn btn-light">Nouveau Réservation</button></a>
    <style>
      h2{
         padding: 5%;
         font-family: 'Playfair Display', serif;
         color: rgb(252, 252, 250);
         font-size:35px;
         text-shadow: 3px 4px 0 rgba(14, 12, 12, 0.2); 
      }
      button{
          margin-bottom:100px;
      }
    </style>
{% endblock %}

templates/reservationfleur/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reservation Fleur De Lys{% endblock %}

{% block body %}
    <h1>Nouveau Réservation Fleur De Lys</h1><br><br>
    <center><h2 style="font-family:'Times New Roman', Times, serif;">Bonjour ! Comment vous appelez-vous ?</h2></center>
    <div class="form">{{ include('reservationfleur/_form.html.twig') }}</div>

    <a href="{{ path('reservationfleur_index') }}"> <button  class="btn btn-secondary" style=" margin:5px 0 100px 200px;">Voir La Liste</button></a>
<style>
h1{
    padding: 5%;

    font-family: 'Playfair Display', serif;
    color: rgb(252, 252, 250);
  font-size:35px;
  text-shadow: 3px 4px 0 rgba(14, 12, 12, 0.2); 
}
.form{
    margin:0 200px 0 200px;
}

button {
   
    width:200px;
    font-size:10px;
    margin-bottom:5px;
}

</style>
{% endblock %}

templates/reservationfleur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation Fleur De Lys{% endblock %}

{% block body %}
    <h1>Réservation Fleur De Lys</h1>

    <table class="table">
        <tbody>
           
            <tr>
                <th>Nom_user</th>
                <td>{{ reservationfleur.User }}</td>
            </tr>
            <tr>
                <th>End_date</th>
                <td>{{ reservationfleur.startDate ? reservationfleur.startDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Start_date</th>
                <td>{{ reservationfleur.endDate ? reservationfleur.endDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Nbr_personne</th>
                <td>{{ reservationfleur.nbrPersonne }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ reservationfleur.description }}</td>
            </tr>
        </tbody>
    </table>
    <div>
    <a href="{{ path('reservationfleur_index') }}"><button class="btn btn-light" >Voir La Liste</button></a> {{ include('reservationfleur/_delete_form.html.twig') }}
    </div>
     <style>
      h1{
         padding: 5%;
         font-family: 'Playfair Display', serif;
         color: rgb(252, 252, 250);
         font-size:35px;
         text-shadow: 3px 4px 0 rgba(14, 12, 12, 0.2); 
      }
    </style>

   
{% endblock %}